#********************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License 2.0 which is available at
# http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#*******************************************************************************/

[build.env]
passthrough = ["RUSTFLAGS"]

# In cross 0.25 the riscv image does not contain cmake making the Rust protobuf build fail.
# (in amd and arm64 image no action needed, as cmake is already there)
# we can not use the version form apt, as this image is based Ubuntu 18 where
# cmake is too old
# This assumes x64 build machiine, adapt cmake download link for arm64
[target.riscv64gc-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install --assume-yes wget",
    "wget -qO- https://cmake.org/files/v3.16/cmake-3.16.7-Linux-x86_64.tar.gz  | tar xvzf -",
    "ln -sf /cmake-3.16.7-Linux-x86_64/bin/* /usr/bin/"
]
