# /********************************************************************************
# * Copyright (c) 2024 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

FROM mcr.microsoft.com/devcontainers/rust:1-1-bullseye
ENV CROSS_CONTAINER_IN_CONTAINER=true
USER vscode
RUN cargo install cross cargo-license cargo-cyclonedx